name: Trainstore
main: net.siebentupel.trainstore.Trainstore
version: 0.1
commands:
  ts-set-destination:
   description: set the destination for a player.
   usage: /<command> [destination]
   permission: <plugin name>.destination.set
   permission-message: You don't have <permission>
  ts-clear-destination:
    description: clear the destination of a player.
    usage: /<command>
    permission: <plugin name>.destination.clear
    permission-message: You don't have <permission>
  ts-destination:
    description: get the current destination of a player.
    usage: /<command>
    permission: <plugin name>.destination.get
    permission-message: You don't have <permission>
  ts-list-stations:
    description: list all stations.
    usage: /<command>
    permission: <plugin name>.station.list
    permission-message: You don't have <permission>
permissions:
  destination.set:
    description: set a destination for oneself
    default: true
  destination.clear:
    description: clear destination for oneself
    default: true
  destination.get:
    description: get current destination for oneself
    default: true
  station.list:
    description: list all stations
    default: true
